[package]
name = "ash-test"
version = "0.1.0"
authors = ["Anton Vladimirov <styleex@inbox.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ash = "0.32.1"
winit = "0.25.0"
num = "0.4"
memoffset = "0.6.4"
